### ISSUE TITLE
Chat prefix doesn't show up

### ISSUE THREAD

**Issue by LyraGhost** [zachoooo/ZavAutoMessager#3]
The messages are showing up but theres no prefix.
The prefix is there for the first few messages, but after a bit it disappears.
It seemed to be affected by commands being run? im not really sure what caused it.

**Comment by zachoooo** [comment]
Can you send me a copy of your configuration, any error messages that you're getting, and any commands that you're running that affects this? Thanks.

**Comment by zachoooo** [comment]
@LyraGhost Please see the above comment

**Comment by zachoooo** [comment]
Marked as Invalid. Cannot reproduce and no message from original ticket creator.
